import Head from 'next/head'
import Link from 'next/link'
import { Footer } from 'src/components/Footer';
import { Main } from 'src/components/Main';
import { Header } from 'src/components/Header';
import { useState } from 'react';


export default function Home() {
  const [count, setCount] = useState(1)
  
  const handleClick = ((e)=>{
    setCount((count)=>count+1);
    setCount((count)=>count+1);
  },[]);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <h1>{count}</h1>
      <button  href="/about" onClick={handleClick}>ボタン</button>
      <Main page="index"/>

      <Footer/>
    </>
  );
}
