import Head from 'next/head'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import { Footer } from 'src/components/Footer';
import { Main } from 'src/components/Main';
import { Header } from 'src/components/Header';
import { useCallback } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const foo = 1
  
  const handleClick = useCallback((e)=>{
    console.log(e.target.href);
    e.preventDefault();
    alert(foo);
  },[]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Link  href="/about" onClick={handleClick}>ボタン</Link>
      <Main page="index"/>

      <Footer/>
    </>
  );
}
