import Head from 'next/head'
import { Footer } from 'src/components/Footer';
import { Main } from 'src/components/Main';
import { Header } from 'src/components/Header';
import { useCallback , useState , useEffect} from 'react';


export default function Home() {
  const [count, setCount] = useState(1);
  const [text, setText] = useState("");
  const [isShow, setIsShow] = useState(true);
  
  const handleChange = useCallback((e) =>{
    if(e.target.value.length > 5){
      alert("５文字を超えています");
      return ;
    }
    setText(e.target.value.trim());
  },[]);
  
  const handleDisplay = ()=>{
    setIsShow((isShow) => !isShow);
  }
  
  const handleClick = useCallback(()=>{
    if(count<10){
      setCount((count)=>count+1);
    }
  },[count]);

  useEffect(() =>{
    console.log('foo')
    document.body.style.backgroundColor = "lightblue";
    return () =>{
      document.body.style.backgroundColor = "";
    }
  },[count])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      {isShow ?<h1>{count}</h1>:null}
      <button onClick={handleClick}>ボタン</button>
      <button onClick={handleDisplay}>{isShow ? "非表示": "表示"}</button>
      <input type="text" value={text} onChange={handleChange}/>
      <Main page="index"/>
      <Footer/>
    </>
  );
}
